run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - misspell
    - gosec

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/malagant/fluxcli

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
