name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  lint-docs:
    name: Lint Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
      
    - name: Lint Markdown files
      run: markdownlint README.md docs/**/*.md --config .markdownlint.json || true

  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdown-link-check
      run: npm install -g markdown-link-check
      
    - name: Check links in README
      run: markdown-link-check README.md --config .markdown-link-check.json || true
      
    - name: Check links in docs
      run: find docs -name "*.md" -exec markdown-link-check {} --config .markdown-link-check.json \; || true

  generate-cli-docs:
    name: Generate CLI Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Build FluxCLI
      run: go build -o fluxcli .
      
    - name: Generate CLI help docs
      run: |
        mkdir -p docs/cli
        ./fluxcli --help > docs/cli/help.txt
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/cli/help.txt
        git diff --staged --quiet || git commit -m "docs: update CLI help documentation [skip ci]"
        git push
